Document History

02/10/2022 Commenced

11/12/2022 First draft for review

04/03/2023 Revision based on review comments

©Daniel Feiglin, 2023

dilogsys@inter.net.il

{empty}(052) 386 9986

ספר שמות פרק כ

(ה) לֹא תִשְׁתַּחֲוֶה לָהֶם וְלֹא תָעָבְדֵם כִּי אָנֹכִי יְהֹוָה אֱלֹהֶיךָ אֵל קַנָּא פֹּקֵד עֲוֹן אָבֹת עַל
בָּנִים עַל שִׁלֵּשִׁים וְעַל רִבֵּעִים לְשׂנְאָי:

ספר שמות פרק לד

(ו) וַיַּעֲבֹר יְהֹוָה עַל פָּנָיו וַיִּקְרָא יְהֹוָה יְהֹוָה אֵל רַחוּם וְחַנּוּן אֶרֶךְ אַפַּיִם וְרַב חֶסֶד
וֶאֱמֶת:

(ז) נֹצֵר חֶסֶד לָאֲלָפִים נֹשֵׂא עָוֹן וָפֶשַׁע וְחַטָּאָה וְנַקֵּה לֹא יְנַקֶּה פֹּקֵד עֲוֹן אָבוֹת עַל בָּנִים
וְעַל בְּנֵי בָנִים עַל שִׁלֵּשִׁים וְעַל רִבֵּעִים:

ספר במדבר פרק יד

(יח) יְהֹוָה אֶרֶךְ אַפַּיִם וְרַב חֶסֶד נֹשֵׂא עָוֹן וָפָשַׁע וְנַקֵּה לֹא יְנַקֶּה פֹּקֵד עֲוֹן אָבוֹת עַל
בָּנִים עַל שִׁלֵּשִׁים וְעַל רִבֵּעִים:

ספר דברים פרק ה

(ט) לֹא תִשְׁתַּחֲוֶה לָהֶם וְלֹא תָעָבְדֵם כִּי אָנֹכִי יְהֹוָה אֱלֹהֶיךָ אֵל קַנָּא פֹּקֵד עֲוֹן אָבוֹת עַל
בָּנִים וְעַל שִׁלֵּשִׁים וְעַל רִבֵּעִים לְשׂנְאָי:

== What Does it Mean?

The expression פֹּקֵד עֲוֹן אָבֹת עַל בָּנִים עַל שִׁלֵּשִׁים וְעַל רִבֵּעִים appears in both
versions of the Ten Commandments and in both versions of the Midot,
thirteen in ספר שמות and nine in ספר במדבר. I am not going to survey the
מפורשים here. See [.underline]#References# below for further details.

I understand the expression, in its fullest form in שמות 34:6-7, as a
historiosophic statement. The segment that I will discuss here is, פֹּקֵד
עֲוֹן אָבוֹת עַל בָּנִים וְעַל בְּנֵי בָנִים עַל שִׁלֵּשִׁים וְעַל רִבֵּעִים.

It is quite common for commentators to take the view that the effect of
sin percolates down to the fourth generation of the perpetrators. They
are not much more specific. They could not be more specific since it is
only in our time can we point to a specific act of evil, the Shoah, that
stands out as a “black tower of evil” in the general swirl of horror
that makes up most of what we call history. We can look at its outcome,
being three to four generations after.

I need to clarify an additional issue: The expression, פֹּקֵד עֲוֹן אָבוֹת עַל
בָּנִים וְעַל בְּנֵי בָנִים עַל שִׁלֵּשִׁים וְעַל רִבֵּעִים carries an oft ignored double
message: It is universally applied to the perpetrators of evil. It is
however, also relevant to the survivors of the evil.

Furthermore, the histriosophic character of the expression is not just
political. It touches on the psychology, sociology, anthropology and
perhaps other aspects of the perpetrator and survivor groups.

== Perpetrators and Survivors

Since we are considering two distinct populations over time, I will make
my terminology more precise:

The perpetrators are those who committed the evil: In relation to the
Shoah, we are dealing with the Nazi party, the German nation and other
nations that actively assisted them in their implementation the Final
Solution. There were further collaborating nations who either did
nothing or who for example, closed their borders to Jewish refugees. The
perpetrators and their descendants are the *Perpetrators Group*.

The survivors are simply those who were able to walk out of the Nazi
hell. The *Survivor* *Group* includes of course, the survivors and their
descendants. I also include in this group, “fringe” cases like my own
mother: Her parents sent her with her elder married sister from Antwerp
to Australia during mid-1939. Her parents remained in Antwerp and were
murdered in Auschwitz-Birkenau during 1943. The two sisters remained in
Australia and raised families.

Strangely enough, the two groups are not mutually exclusive: Some
victims collaborated, whether willingly or not: We all know about the
Judenrate and the Kapos. In the opposite direction, there were members
of the Perpetrator group who opted out, often at the cost of their
lives. We will not deal with these cases here: They were largely local
groups or individuals.

At the time of writing, 10/2022, most of the perpetrators are dead of
old age. The original survivors are also a dwindling group of some tens
of thousands.

In the following sections, I will deal with the Survivor Group first and
then the Perpetrators Group.

== The Survivor Group

Since this is not a scientific note, I will continue with my personal
story for illustrative purposes.

There are two ways to view “the fourth generation”:

There is the conventional demographic way of treating a generation as
being about 25 years. So, 1945 to 2020 covers three generations and the
fourth is of course from 2025 to 2045.

There is also the simple way of counting generations. It is not as
unambiguous as it seems.

My wife is the daughter of survivors: Her mother was at Auschwitz for
several months and was liberated by the Russians in January, 1945. Her
father was drafted into forced labor in Hungary in 1940 and escaped
towards the end of the war as the Russian forces moved west. That makes
her first generation, our five children second generation, our 28 (so
far) grandchildren third generation and our 2 (so far) great
grandchildren, fourth generation.

Now look at my side: My mother is first generation (her parents were
still alive when she married), I am second generation, my children are
third generation and my grandchildren are fourth generation!

So, it’s not that clear cut. I would suggest, that the current Survivor
Group status is already fourth generation, but it is still too young to
have acquired notable historic characteristics. I would however, claim
that the fourth generation is in its early 20s, rather older than the
conventional 25-year model would have it.

How did the Shoah experience affect the survivor group?

There have been extensive studies on this and I would like to restrict
myself to a few personal observations:

The survivors themselves were all different. (I grew up in a community
with many survivors.) I learned very early that there was no yardstick
to judge the behavior of survivors – that ranged from violently deranged
to superficially normal. My parents-in-law fitted into the latter
category. That of course also affected their children. I saw that in my
own household and in others – but I am too close to it to be objective.

The second generation, my children are quite different. Like the
majority of known Jewish children of their age group – who now live in
Israel – they are beset with their own existential issues and are less
concerned about their family background. Having said that, there is a
resurgence of interest as they get older, with children of their own.
So, the second generation (by my wife’s line) has only been
superficially affected by any “post Shoah mentality”. Interest in the
subject among my children varies from heavy to zero.

The third generation is even less affected. Once a year there is יום
השואה והגבורה at school and that’s it. The Israeli milieu has taken over
completely.

I suspect that this situation is rather widespread in Israel. I do not
know if my observations are valid for last three generations in חו"ל.

After 3.5 generations, the effects of the Nazi venom have largely been
expunged from our children. What (I hope) will remain, will be an
educated objective view (כבדהו וחשדיהו) of whom exactly we are dealing
with outside of Israel.

== The Perpetrators Group

מחזור ספרד לראש השנה - מוסף לראש השנה:

וְעַל הַמְּדִינוֹת בּוֹ יֵאָמֵר אֵיזוֹ לַחֶרֶב, וְאֵיזוֹ לַשָּׁלוֹם, אֵיזוֹ לָרָעָב, וְאֵיזוֹ לָשּבַע,
וּבְרִיּוֹת בּוֹ יִפָּקֵדוּ לְהַזְכִּירָם לְחַיִּים וְלַמָּוֶת:

Again, I return to the expression, פֹּקֵד עֲוֹן אָבוֹת עַל בָּנִים וְעַל בְּנֵי בָנִים עַל
שִׁלֵּשִׁים וְעַל רִבֵּעִים:

We see it operating before our eyes:

=== Europe – The Charnel House of Israel

Overall, the Europeans have learned nothing from the Shoah. We are now
somewhere between 3 and 4 generations since the Shoah. European
civilization is gradually being replaced with a crude fundamentalist
Islamic immigrant society.

The Europeans have quietly replaced their old-fashioned antisemitism
with a crocodile-teared support for the “human rights” of the
Palestinians, a “nation” contrived by the Soviet KGB in 1964 for Cold
War political purposes. Much of the funding for the so-called
Palestinian NGOs comes from Europefootnote:[See
https://www.ngo-monitor.org/[NGO Monitor]].

European politicians (and indeed the EU in Brussels) now have a large
Muslim electorate. That also, is accelerating the transition of Europe
to Eurabia.

The attitude towards Israel and the Jews of the Vatican has not changed
even if it comes wrapped in occasional vague soporific statements. The
French remain – themselves. The Poles are busy trying to whitewash their
role in the Shoah. The most amusing (sic!) group are the Ukrainians
currently at war with Russia. I wish both sides success.

The UK is in some ways a special case, having had very mixed relations
with Israel (in the broadest sense). The UK did not cause the Shoah, but
did sit and do nothing to prevent it or alleviate its worst effects.

The UK has oscillated between the Norwich massacre of 1190, the 1290
expulsion, the Balfour declaration of 1917 and its behavior during the
mandate period. The UK has also a large migrant population, dominantly
Muslim. The UK fourth generation could go in either direction.

=== The USA

The USA did not cause the Shoah, but did sit and do nothing to prevent
it or alleviate its worst effects.

Anyone who has followed US relations with the world Jewish communities
over the last 100 years or so culminating in her relations with the
State of Israel, will observe a great deal of ambivalence, occasional
flashes of support and much antagonism. The key factors are the
influence of the largely pro-Arab State Department, the Defense
establishment, the strength of the Presidency and commercial interests.
The USA is deep into its own “fourth generation” woes with the Biden
presidency.

Virulent antisemitism is not endemic in the USA as it is in Europe.
There is still a chance for the USA to pull out of a pending collapse
but the window of opportunity is rapidly closing.

=== The Middle East

The Sunni Arab countries generally supported Nazi Germany and during the
early 1950s expelled their remaining Jewish populations. Apart from the
Saudis and the Emirates, they are for most part failed states.
Curiously, the latter are slowly “coming around” from their apparent
blind support for the “Palestinian Cause” and may get past the “fourth
generation syndrome”.

The Iranians are in the throes of a revolution so it is impossible to
say where they will “land”.

=== The Near East

India is a very interesting case: From about 1991, India has had formal
and warm relations with Israel. India, as a British colony during the
Shoah had no part in it and is not subject to the “fourth generation
syndrome”.

=== The Far East

Japan, although an Axis power, did not cooperate with the Nazis in
respect of the Jews. Japan’s behavior was quite reasonable and is also
not subject to the “fourth generation syndrome”.

The same would be true for China. I would expect North Korea (as a major
technology supplier to the Iranian Mullahs) to collapse in a further
generation, for other reasons.

=== Africa and South America

I do not have any view on these continents whose constituent states
either did not exist or if they did, they had little influence on the
Shoah for better or for worse.

== Where it Does Not Apply

The three-four generation criterion (micro) is not a replacement for a
theory of the rise and fall of civilizations (macro). Does the Torah
have something to say about civilizations? Indeed, it does – in פרשת
האזינו. See my note on that.

== Conclusions

Over and above what I have written, are there any conclusions? It is
paradoxical that the greatest act of unbridled evil I recorded human
history offers an affirmation of Mosaic historiosophy and hence a way to
understand emerging world events insofar as they affect us.

== References

Here are several links to traditional discussions of the
fourth-generation issue:

[arabic]
. https://he.wikisource.org/wiki/%D7%91%D7%99%D7%90%D7%95%D7%A8:%D7%A4%D7%95%D7%A7%D7%93_%D7%A2%D7%95%D7%95%D7%9F[WikiText]
. https://tora.us.fm/tnk1/kma/qjrim1/pdqewn.html[Tora.us]
. https://www.aspaklaria.info/001_ALEF/%D7%90%D7%9C%D7%A7%D7%99%D7%9D%20%20%20%D7%A4%D7%95%D7%A7%D7%93%20%D7%A2%D7%95%D7%9F%20%D7%90%D7%91%D7%95%D7%AA.htm[Aspaklaria]
