== The End

Knock, knock, knock!

I glanced aside from the computer monitor to the door. Who, for heaven's
sake, could be looking for me, here of all places, at eleven o'clock at
night?

For years, I maintained a workroom away from the house, next to the
settlement secretariat. That way I could get on with my business free
from domestic interference and unwanted visitors.

"Come in!"

A man of medium height, wearing a grey raincoat, opened the door. He
wore a grey hat pulled down over his forehead somewhat obscuring his
face. The raincoat seemed out of place on this late March spring
evening. The rains had come and gone.

The man entered somewhat diffidently, looked about as if unsure of
himself, and then asked me, "Are you Saba Savion?"

His voice told me nothing.

"Sure. And with whom do I have the honor?"

He half smiled at my barely hidden annoyance at the interruption.
Without troubling to identify himself, he asked, "Do you mind if I sit
down?” occupying the chair across from my table as he spoke.

A big blowfly buzzed in the still open door and proceeded to make noisy
circuits of the room. Both of us glanced up at the blowfly. He smiled
again, rose and closed the door.

"I'm sorry about that", he said, resuming his seat, "I suppose you want
to know what this is all about."

"I can hardly wait."

"What I have to tell you might be a bit hard to take."

"Who died?"

"You!"

"Come on, cut the crap!"

"Look at the blow fly!"

I had forgotten about the pesky blowfly. After a moment I located it. It
seemed to be stationary, in midair, not doing anything.

"Do you notice something odd about the fly?" the man asked.

" It seems frozen in midair!"

We both remained silent, watching the fly for a few moments. I noticed
that the room seemed to be enveloped in silence. The music CD ROM on the
computer had stopped playing, and in fact I could no longer hear the
buzz of the computer's cooling fan. I noticed that the digital display
on the computer box was flicking on and off ad a very slow rate. The
video screen also seemed to rise and fall in intensity, as if a long
power wave was washing over it.

Exasperation started to creep over me.

"You were going to tell me what this is all about", I reminded him.

"You are experiencing your last heart beat", answered the man opposite
me.

"Rubbish. A heartbeat takes less than a second. We've been sitting
around talking for about three minutes - why even this remark ran to
about ten seconds!"

"No, no. It's not quite that simple. You are now operating in a form of
psychological time which can be quite independent of biological time."

"And you I suppose, are the much to be feared Angel of Death?"

He merely smiled and said nothing.

"That's very funny", I continued. "The least you could have turned on
was a dangling skeleton with a scythe or maybe scary red devil with a
red hot pitch fork. What do I get? A man dressed in a grey hat and
raincoat. And anyway, for how psychologically long can the last
heartbeat go on? A minute? An hour? A year?"

The man opposite me sighed.

"Where should I begin?" he mused, as if to himself. He paused for a
moment and continued:

"The Angel of Death does not exist. What people, or as I prefer to think
of them, my clients perceive in their last heart beat is a product of
their own accumulated fears, expectations and preconceptions."

"And you are a product of my fears, expectations and preconceptions?"

"More or less. And as to how long this form of psychological time can
last, your intuition was correct. It can be indefinite."

"The whole thing sounds like a crashing bore to me."

"Actually, it could be far worse than that."

"How so?"

"At a certain point a client finds that he has nothing further to say to
me."

"And then you whip him off into good old eternity?"

"No. I am not that crude. Even in my profession there is room for
finesse and elegance. I always offer my clients an opportunity to rerun
their lives."

"Something like a home video movie?" I prompted.

"Almost. Much more realistic."

"I cannot imagine why people would want such a thing", I mused.

"Most of them seem to want that more than anything else."

" It smacks to me a bit like narcissism. Maybe just stalling. And you
offer this all in the space of a heartbeat?"

"Yes, but only the last heartbeat. And you are right. It is a bit
narcissist. The reactions of my clients seeing themselves as they really
are, provide them with a never-ending source of wonder. As for stalling,
who cares? As you correctly intuited, I have all eternity. Would you
like to try it?"

"I have a question for you Mr. Angel of Death or whatever in a grey hat
and raincoat."

The man opposite me cocked up his eyebrows and a faint grin crossed his
face. "Ask, and all will be answered my son", he said in a mockingly
unctuous tone.

"Suppose", I began, "that I accept your proposition. You replay my life
for me. What happens when we get to the point of my last heart beat? Do
we go through this little comedy again?"

"Let us suppose", he replied.

"So", I continued, with a triumphant note in my voice, "it seems that I
would ultimately find myself in an infinitely recursive loop, from which
there is no break out. Why not? You agreed with me that you had all
eternity!"

"I can see that you are going to be a difficult client"

"Listen to him", I jibed as if to no one in particular, "I have just
been offered a one-way ticket on an endless roller coaster ride to
nowhere, all in the space of a heart beat and I'm meant to take it
seriously!"

The man started to say something, but I interrupted.

"I haven't finished. The fact that I can experience anything at all,
even in the space of one heartbeat points my not being totally removed
from the world of reality, from which I presumably came."

" So?"

"That means that each successive repetition of my life story is going to
take place in a shorter portion of my last heartbeat. In fact, the
portions would have to decrease for example, geometrically to ensure
that I remain within that bound. Now then", I continued, adopting the
pose of a university professor, "if each replay takes less physical time
than its predecessor, and if indeed, the ability to stage the replay
requires contact, be it of the most tenuous kind, with the world of
reality, say for example, my own store of memories, then we have to face
a bogey called entropy."

"What's the point?"

"The point is very simply loss of information from run to run.
Attenuation. Like the wear and tear effect that would become
progressively noticeable if you replayed the same home video 10, 100,
1000 times. Ergo: Beyond a certain point the replay of my life would run
to noisy mush, and eventually pure white noise. Is that by any chance
what you call Hell?"

" I knew that you were going to be difficult."

" Tell me something else", I continued, " What does your employer think
of the 'heads I win, tails you lose' deal you're offering me?"

The man shrugged. "It's the same deal I offer everyone."

"You haven't answered my question!” I persisted, "What does your
employer say?"

"Why don't you ask my employer yourself?” he snapped back petulantly.

"How?” I asked.

"You've had a life time to figure that out for yourself."

For a few moments, we looked at each other across the table without
speaking.

"You said", I proffered, " that you would answer any questions that I
asked."

"Correct."

"You didn't answer my question about the way of talking to your
employer. You just returned a clever riposte. That is not an answer."

"I don't think that you are exactly in a position to tell me what is or
isn't an answer"

"We'll see", I said, the germ of an idea forming in my mind.

"Is there a break out possibility from the infinite loop?"

"Yes."

"Is it attainable through the use of human reasoning?"

"Yes."

Carefully, now:

"Can I refuse to accept your offer?"

"No. Not really."

"Assume for a moment, that I discover how to break out from all of this.
Does the alternative differ significantly from what you are offering?"

"Yes."

"Does it entail ultimate oblivion as does your offer?"

"Only my employer could answer that."

"Do you know in advance, with absolute certainty, how any given client
will behave? What foreknowledge do you have?"

"To your first question, no, to your second question, I receive a full
dossier from Central Records on each client. As you probably know, my
employer updates them annually. Only my employer has the kind of
foreknowledge you imply."

"Do you mind if I have a few minutes to think?"

"Take all eternity, so far as I am concerned!"

I stood up from my chair, and started to pace up and down as if
engrossed in deep thought. The man simply watched me. On each pass back
and forth behind my desk, I added a centimeter of distance. So, the man
was an unstoppable executioner, but not a mind reader.

After several hundred years of elapsed psychological time, I maneuvered
myself to within a centimeter of the door.

Without so much as an inkling of warning, I threw it open and stepped
outside, into ...

____________________

== The Beginning

I woke up as if from a long deep sleep, in a patch of soft dry grass.
Around me were trees and bushes, laid out as in what appeared to be a
sort of botanical garden. From time to time small animals would dart out
from the foliage only to disappear with equal swiftness. I noticed
larger shapes moving in the distant shadows, evidencing larger animals.
Birds fluttered and twittered among the branches of the trees. The
whispering rush of a nearby brook completed the idyll.

I moved my limbs, stretched and breathed deeply. I had an odd feeling
that I was somehow disjointed from my body. It moved to my thoughts and
feelings yet it was not quite me.

I overheard the voice of the man I had just left in a quiet conversation
with someone else, also unseen.

"What do you think about these?” asked the man, "Will they be better
than the last ones?"

"Hard to say", came the answer, "Where did you put the other..."

"I merged them for easy transfer..."

The voices drifted away.

Left to myself, I started to visually explore myself and then my
surroundings. Again, I tried to stretch, and wiggle my toes.

"Umm", purred a female voice almost from inside my own head, "that's
nice!"

"Who on earth is that?” I thought-said to one in particular.

My answer came almost immediately. Firmly, but very gently, my visual
and mental perspective started to distort - no, not distort but
transform into that of a female. And then it snapped back to normal.

Again, the same female voice as before, "Oops, I beg your pardon! I
haven't quite figured out how to go through our senses without bumping."

"Our senses?” I asked-thought, "What's going on here?"

"Can't you see?” replied the female voice, this time with a tinkling
laugh, "There are two of here! Look, close your eyes, shut off your ears
and come inside yourself!"

I followed the voice's instructions without demur.

Instantly I found myself locked in an emotional embrace, which washed
around my senses hearing lights, seeing smells and smelling sights. The
tactile sense was exquisite, yet entirely absent. Most of all, the sense
of simultaneous unity and individuality tore at my senses like the
irresistible pull of a whirlpool. Then a slow but persistent feeling of
withdrawal, of separation, accompanied by just a touch of the sorrow of
departure.

It was an intimacy, which transcended male female contact, dwarfing any
residual sexual impulses remaining in either of us.

I slowly recovered my senses, but I knew that I was not alone. There was
an emotional after-glow, not of my own person, nor of my own making.
Behind the smile I felt playing on my face, there was another smile, no,
again, the tinkling laugh.

I or should I say we, were bounced back to reality by the sound of a
familiar voice -

"Yes, I think they are ready for the next stage," said the man, now
without grey hat or raincoat.

"Uh oh", I thought to myself, "This looks like trouble!"

The female voice came in, "Yes I remember him. He looked like the
headmaster at my school when I was a kid. He used to scare the daylights
out of us! How did he appear to you?"

I told her. She chuckled dryly.

"You got off lightly. I started to scream for help, and I finished up
diving out of a fourth storey window."

I shared her shudder of fear and revulsion from the recollection. It
felt like a punch in the stomach.

Our conversation was interrupted by the appearance of the man in front
of us, directly in our line of sight. Over to the right there appeared a
shimmering circular glowing form, which might just have had some of the
features of a human head but not quite. I-we stood up shakily.

"Good", said the man in a tone of self-satisfaction, "You seem to have
found yourself. Do you have any idea where you are?"

His glibness annoyed me.

"I'm with Alice in Wonderland", I replied. "This is evidently the Mad
Hatter's tea party, you are the White Hare and yonder face", I said
pointing to the shimmering head-no head, "is the Cheshire Cat."

The man's face clouded over with anger.

"I'll have you know that this is anything but Wonderland, I'm no White
Hare and what you called the Cheshire cat is my Employer, you - you Door
Mouse!"

"At least Alice is real enough." I was determined to have the last word,
but to no avail.

"Enough", thundered a voice from the shimmering head-no head. "Now that
you have finished identifying White Hares, Cheshire Cats and doubtlessly
other sundry wildlife, we might as well get down to business. Separate
them!"

"Now you've done it", wailed the female voice from inside me. I detected
a small sob, felt a teardrop, and then nothing.

_______________

== Awakening

I woke up as if from a long deep sleep, in a patch of soft dry grass.
Around me were trees and bushes, laid out as in what appeared to be a
sort of botanical garden. From time to time small animals would dart out
from the foliage only to disappear with equal swiftness. I noticed
larger shapes moving in the distant shadows, evidencing larger animals.
Birds fluttered and twittered among the branches of the trees. The
whispering rush of a nearby brook completed the idyll.

I moved my limbs, stretched and breathed deeply and sat up. Alongside me
slowly coming awake, lay the most sublimely beautiful female, I could
ever have hoped to see. We were both stark naked, with young the healthy
bodies of about twenty year old biological age. We looked at each other
without a trace of coyness.

Without exchanging a word, we both sensed that we had been endowed with
the knowledge and the experience of old, very old people, alive maybe
thousands of years, the accrued Wisdom of Generations. We were a pair of
ancient twenty year olds.

We barely had time to get to our feet, when a stentorian voice thundered
out:

"From any of the trees you may eat; but from the Tree of Knowledge of
Good and Evil, you shall not eat. For on the day you eat there from, you
will not live beyond the space of a heartbeat..."

== Document History:

© Daniel Feiglin, 02/02/1996

06/02/1996 Original

21/08/2020 Minor typo corrections
