== Knowledge

And so, Adam knew his wife, Eve.

I came awake first. Eve was still asleep. Eve? For the first time I had
thought of her as Eve rather than “the girl”.

By throwing the forbidden fruit in Snike’s face she had certainly
changed “the game”. But how? I felt that I needed to speak to *Him*.

I half thought, half said to myself, “We’ve spoken before …”

*“I have something for you.”*

“I wanted to ask a few questions. The situation is unexpected … weird.”

*“You have just passed your first test.”*

“Why do you have to test us – as if you don’t know the answers?”

“The test was for both of you to help you understand yourselves.”

“I think that Eve should be in on this conversation.”

“She is.”

I looked to Eve. She was sitting up. The grassy knoll Eve had been lying
on, took the form of an armchair. She was sitting with her hand holding
her chin and a concerned look on her face.

“And so, I have something for you. Please approach the Tree of Life. It
is near Ground Zero.”

Once again, we walked over to the Notice Display and observed where we
were relative to Ground Zero and the Tree of Knowledge of Good and Evil.
We held hands and for the second time … woof … we were standing just
outside Ground Zero.

This time Snike was standing outside the ring of colored stones, next to
a miserable looking sapling about a meter tall with a few dry leaves
dangling of a single thin branch.

“Where is the Tree of Life?”

“You are looking at it.”

== The Tree of Life

Eve approached the sapling, bent over, carefully taking one of the dry
leaves between her fingers, and smelt it. “Odd”, she mused. “Snike!”

“Yes?”

“Can you bring a watering can?”

In an instant, Snike proffered a watering can to Eve.

“Thank you.” She looked at the watering can. It is empty. “Snike! You …
dolt! What am I supposed to do with an empty watering can?”

“Your instructions to me must be precise whether verbal or mental. One
moment.”

“Now look behind you.”

We both turned around. There is a rise about two meters high. It is lush
green on both sides. In the middle a small spring was bubbling down over
a rocky bed. Eve walked over to the spring, filled the watering can and
returned to the sapling.

“Eve, just a few drops on that sapling.”

Eve sprinkled a few drops of water on the sapling. The sapling started
to grow into a small leafy shrub. It reached about two meters high and
stopped growing. It has no visible fruit. I wondered aloud:

“Doesn’t the Tree of Life have fruit?’

“The difference between the Tree of Knowledge of Good and Evil and the
Tree of Life is that from the Tree of Knowledge you can eat of the fruit
and bear the consequences whereas you have to bring something to the
Tree of Life for it to open up to you. You saw how it responded to a few
drops of water from the spring. The Tree of Life is its own fruit.”

Eve eyed Snike and with a strange look of determination on her face. She
sloshed the newly sprouted shrub with the remaining water in the can.

The ground started to tremble around the small shrub and we quickly
backed off. It suddenly shot up into the sky overshadowing the Tree of
Knowledge of Good and Evil in the middle of Ground Zero.

“I told you a few drops … but Eve, you think that you are smart. Now see
what happens.”

“Snike! Bring them both a cup of water from the spring.”

A moment later, Snike handed each of us, a cup of water. We both drank
it down and returned the cups.

“Approach the Tree of Life and touch it!”

Eve and I approached the tree. It had thick branches covered with broad
green leaves and still no visible fruit. Eve and I looked at each other
apprehensively, and we both touched the tree.

== Dozakh

… and suddenly we were standing together, outside a cave in a small
mountain in the middle of a hot desert. We were both covered in a sort
of one-piece robe with full sleeves and trouser legs It was laced up at
the front. We both wore slippers welded to the end of our trouser legs.
The top of the robe was a hood that we could throw off or pull down and
close with a pair of cords near the neck. When closed, we found that the
hood was quite transparent and did not impair our breathing.

“I am giving you a problem to solve. This place is known as Dozakh.
While you are here, you should not eat or drink anything. The cup of
water you drank before arriving here will sustain you. You are otherwise
normal humans with a few special advantages: Your clothing will protect
you against the elements and man-made weapons. Snike will accompany you
and provide you with such assistance as you might need. Now, look out
across the desert. Just right of center you will see a brownish patch on
the horizon. That is Dozakh city, to where you will go. The city sits in
a lush area watered year-round by a river. The civilization you will
find there is agricultural and bronze-age. The rest you will see for
yourself and understand very quickly. In addition to the robes you are
wearing, Snike will provide outer robes that will enable you to blend in
to your surroundings without drawing attention to yourselves. Now go.”

I took Eve’s hand and we started trudging towards the city.

“_Ahem_!”, said Snike. “_You are really doing it the hard way_.”

“And what do you propose?”

“Remember, I am here to assist you.”

Slowly: “Alright. Can you place us outside the city? You’d have to be
careful not to have us pop out of nowhere and scare the hell out of
them.”

“Sure. But you can’t scare the hell out of anyone in this place.”

I was sure Snike was smiling.

“When you arrive, you may speak freely to the natives. You know their
language. Between yourselves and me, you can if you wish, also speak in
your own language.”

And … woof … and we were standing about 50 meters from a hard-packed
dirt road leading to the open gate of the city. It was morning and there
was light traffic on the road all heading towards the city gate. It was
mostly people on foot, a few on donkeys and camels. There were also
numerous small horse drawn carts carrying people and produce.

We joined the people on the road. No one took any notice of us. We
arrived at the city gate. The guards gave us a cursory glance and waved
us on.

Inside the city, people were coming out of their houses and moving
toward what appeared to be a tower at the city center. As we moved with
the increasing crowd, the relatively primitive hovels gave way to
well-to-do free-standing villas and then to palaces.

And then we reached the center. The center was a large open stone
semicircular amphitheater dipping down in to the ground. At the end and
in the center was a massive idol with a hideous part animal part human
face.

Most of the front benches were taken by rather well-dressed people.
Those entering with us, took the back benches. Our outer clothing was
apparently “aristocratic” and we found ourselves ushered to the second
row of benches in the center, behind the king and his retinue. As we
took our places, there was a bit of shuffling to the left and right to
make room. Snike was beside us, evidently invisible, undetectable and
taking up no space. The crowd was rather quiet. There was not much
chatter, just whispering and general sense of expectation. Along and
behind the back row, were stationed guards in ceremonial dress and
trumpeters.

The idol in front of us was huge, its base spreading across half the
diameter of the amphitheater.

In front of us to the left were two pens, one holding sheep and goats
and the other holding calves. Further to the left between the benches
and the idol, was a double door in the wall. The area between us and the
idol was an open stone floor, sloping downwards. The last few meters
were smooth stone and quite steep. The slope was enclosed on both sides
by low walls carved to look like feet of the idol. At the end of the
slope was a semicircular opening about three meters high. Inside you
clearly see the flames of a furnace deep in the bowels of the idol. The
heat could be felt as far back as we were.

It looked like we had found our way into sacrificial ceremony. I said as
much to Eve, who just screwed up her nose and said nothing.

The trumpets sounded, and the doors to our left opened. Into the
clearing below us, marched a column of priests dressed in red and gold
lead by a figure who could only be High Priest. They marched all the way
across the clearing and waited. On a second blast from the trumpets, the
High Priest took his place on a dais below us and the other priests
moved to their posts.

The trumpets accompanied by other musical instruments broke into a
harmony that was taken up the crowd singing to the music.

Accompanied by the music and singing, four priests grabbed a calf and a
sheep from the pens and dragged them to the open maw of the idol. The
High Priest raised his hand. The music and singing stopped. The priests
shoved the calf and the sheep down the slope towards the maw of the
idol. There was a hideous shriek of animal pain as the fire took them.
And then silence. The music and singing started again. The animal
sacrifice performance was repeated three or four times. Apart from the
cruel waste of animals, it was boring.

And then there was a completely different trumpet fanfare: Once again
the gates to our left opened: A group of four priests marched out,
escorting about ten young children dressed in long white robes with rope
belts. They had their hands tied in front and then to the rope belt of
the child ahead. As the group moved towards the center the music and
singing started again. Closer up, the children looked drugged. In a
flash without warning the, two priests freed the lead child, a girl, and
heaved her down the slope to the maw of the idol. Again, the scream of
agony and then silence.

Eve threw herself against me and with a wracking shudder, cried out
“STOP IT! STOP IT!”

“Snike! You heard. Stop it! Fill that furnace with water!”

Where a moment ago there was fire, great gouts of steam leapt from the
maw of the idol. A few moments later it disgorged still hot bubbling
water. The priests stood stunned with disbelief. From the crowd there
was muttering and the beginning of movement to leave the amphitheater.

“Snike! I need a voice!”

“You’ve got it.”

“NOW HEAR THIS! ALL OF YOU RETURN TO YOUR PLACES. GO ON! DO AS I SAY AND
NO ONE WILL BE HURT. PRIESTS! STAY WHERE YOU ARE. DO NOT MOVE.”

There were a few minutes of shuffling as the crowd took its places
again.

“NOW PAY ATTENTION! THERE IS ONE GOD WHO CREATED THE HEAVANS AND THE
EARTH. YOU WILL NOT BOW DOWN TO STATUES AND IDOLS LIKE THAT IN FRONT OF
YOU. I WILL DESTROY THEM ALL.”

“Snike! Do it!” There was a great rumble and shaking. The idol
collapsed, disintegrating into gravel and filling the flooded fire pit.
The crowd and the priests were silent and looked stunned.

TO ME, THE GOD, YOUR CREATOR, SHALL YOU BOW DOWN AND OFFER YOUR
SACRIFICES. BRING SACRIFICES FROM THE FIRST OF HERDS, YOUR FLOCKS AND
YOUR PRODUCE.

DO NOT BRING HUMAN SACRIFICES. IT IS ABHORENT TO ME AND I FORBID IT. I
WILL CUT OFF ANYONE TAKING PART IN A HUMAN SACRIFICE. My anger will be
terrible.

“Snike! Those priests! Time for a bolt of lightning.” A bolt of
lightning struck and engulfed the priests. Even odd priests scattered
among the crowd were hit. But no one else, no matter how close. There
was an uneasy sigh from the crowd.

Eve, no longer shuddering, spoke at last. “Snike, those children -
return them to safety.”

“Done.”

The king stood up in front of us and looked around. He saw us and caught
my eye. A look of understanding crossed his face as his hand reached for
the sword in his scabbard. Those in his retinue also reached for their
swords.

“Snike! Back to the cave entrance for us. Now!”

And … woof … and we were standing outside the cave entrance.

== Back at the Tree of Life

“What now?” I asked Snike.

“We return to the Tree of Life. Enter the cave.”

We did so and … found ourselves standing next to the Tree of Life.

I felt exhausted and Eve looked white and shaken.

“Snike! Bring them both a cup of water from the spring.”

A moment later, Snike handed each of us, a cup of water. We both drank
it down and returned the cups. I felt invigorated and Eve regained her
normal color.

“Be seated. Let us review what happened. First, what do you say?”

I thought for a few moments.

“Considering the suddenness of the first human sacrifice I had to act
quickly to prevent a second one. So, I commanded Snike as you saw. My
‘follow up’ was admittedly not very original, but again quick action was
needed.”

“Eve?”

“To ‘solve’ the problem, we would have had to remain on hand for a very
long time, maybe even permanently, forever making corrections.”

“Adam, you jumped in to solve the immediate problem but Eve understands
the consequences, the longer-term issues. It showed up in her command to
Snike, to send the child victims to safety, not to their homes or
families. She considered the possibility that their families were
complicit in sending them to be sacrificed. Between you, you did
reasonably well, but there is a long way to go.”

Something troubled me. “May I ask a question?”

“I know what is troubling you, but ask anyway. Often the asking carries
the answer.”

“In the world of Dozakh we saw evil, terrible evil. Who ate from the
Tree of Knowledge, Good and Evil in their world?”

“Nobody. But you both served as the same ‘trigger function’ in Dozakh
that your predecessors did in the world from which you came. Dozakh is a
world that I created in parallel to the Garden of Eden, in which you
find yourself. You already know that eating this or that fruit does not
create evil. Evil is a consequence of your ‘otherness’ from Me. Your
otherness taken to an extreme by disobeying Me is that which creates
what you call evil. To ensure that you understand this clearly – Snike!
Bring two pieces of fruit from the Tree of Knowledge, Good and Evil at
Ground Zero. Wrap them in leaves from the Tree of life and give them to
Adam and Eve to eat.”

Snike brought the fruit pieces wrapped in the leaves and handed them to
us. Eve and I looked at each other. Somehow, we sensed that something
was about to change.

We both ate the fruit. The refreshment was not just physical. I felt
that an argument of sorts was brewing.

“Let us continue. Your three commandments were a turning point for
Dozakh. Until then, their civilization was an oppressive power structure
based purely on might. Their king is a strong intelligent person who
maintained his status by ruthless cunning. He saw in you, two richly
dressed strangers. He did not recognize you and immediately assumed that
you had something to do with the chaos around the smashed idol and dead
priests. The king did not like your commandments at all. They challenged
his absolute rule. And so, he prepared to deal with you in the only way
he knew. You then ordered Snike to return you to the cave. Recall that I
told you that none of their weapons could harm you. Why did you withdraw
at that point?”

This time Eve cut in: “You said earlier that Adam acted quickly, perhaps
not giving sufficient weight to longer term consequences as I did. Maybe
his impulsive response showed an intuition of which even he was unaware.
Imagine what would have happened had we let the king and his men attack
us. We would have fended them off in some way with minimum casualties,
but we would have left the king looking like a defenseless buffoon in
front of his people. That would probably have triggered a battle for
succession with anarchy and violence ruling the day. And in the chaos,
those three commandments would have been soon forgotten with child
sacrifice re-instituted before you knew it.”

*“Consider Eve’s observation that to ‘solve’ the problem, you would have
had to remain on hand for a very long time, maybe even permanently,
forever making corrections: What might have come out of disposing of the
king and taking his place for the long term?”*

I answered: “I think that not knowing anything about the culture of the
Dozakh society, we would have made a complete mess of it. For one thing,
injecting our ideas of what should be done would be a massive
anachronism. Who knows where that might lead? Our technology in a
century, nuclear wars in two? So, to answer Your question, I think,
not.”

“Good. I am pleased that you both understand that moving into a world
and to use Eve’s notion, making long term corrections, is not black and
white. It is a very subtle, delicate business. Both of you, move to
Ground Zero.”

== Ground Zero

We moved to Ground Zero as instructed.

“Now, you will leave the Garden of Eden to carry out the task that I
have assigned to you. You will go into a world rather more primitive
than Dozakh. You will insinuate yourselves into the local homo-sapiens
population and turn them into human beings. This is a long-term project
that will run to thousands of your years but you have all the time that
you need. You will go yourselves, as normal human beings but with
certain special abilities and tools to enable to carry out your task.
Snike will accompany you to help you adjust to your surroundings,
however after your orientation he will leave you to your own resources.”

“A major part of your ‘toolkit’ is yourselves. Eve will bring your
children into your new world. They will mingle with the indigenous
population. They will not just carry your genes; they will also carry
the values that you teach the first and second generations. And if you
are careful, it will run even deeper.”

“I see from your hearts that you are both troubled. Understand that you
are both much more to Me than a mere agent like Snike. You will both
know when you have done as much as humanly possible to carry out your
task. I give you both my Covenant on this: While you are in your new
world, you may always turn to Me. When you leave that world, you will
both return here to Ground Zero without ever tasting death. Having
returned here you will have acquired the beginning of understanding of
My Plan.”

“Now, approach the Tree of Knowledge of Good and Evil and touch the
trunk.”

We did so, and in an inkling, found ourselves with Snike in a rather
large well lit up cavern.

_“This”_, said Snike, _“Will be your own private Ground Zero in your new
word.”_

== And so, it Begins

And Adam knew Eve his wife; and she conceived and bore Cain, and said:
“I have gotten a man with the help of the Lord.” And again, she bore his
sister, Hevelyn. And Hevelyn domesticated all sorts of strange animals
but Cain could till a patch of sand and make it bloom. And Cain and
Hevelyn got on very well without a trace of sibling rivalry.

* +
*

== Document History:

© Daniel Feiglin, 22/08/2020

22/08/2020 Knowledge, basic outline

21/09/2020 Dozakh (started)

17/10/2020 First draft

19/10/2020 Typos and grammatical corrections
