הנטע אזן הלא ישמע?

אם יצר עין הלא יביט?

תהילים צ"ד:ט

_He that plated the ear, shall he not hear?_

_He that formed the eye, shall he not see?_

Psalms 94:9

הבורא אירוניה יחסר חוש הומור?

_Will the creator of irony lack a sense of humor?_

== Awakening

For a few moments we stood silently, stunned. The girl’s hand slipped
into my own, almost of its own accord. She looked at me – her face
showed a mix of dismay and distaste. I voiced both our feelings –

“Oh, no. Here we go again. Doesn’t it ever stop?”

She dropped my hand.

“I suppose”, she said, “that I have to get ready to replay the role of
the arch-bitch of history to keep a future bunch of self-righteous old
misogynists employed.”

“I wonder”, I replied. “The way in which we both got here suggests that
is room for variation. Maybe this merry-go-round is not entirely
pre-determined.”

“What’s your name?”, she asked.

“Oh, whatever you like”, not wanting to break a train of thought. “What
would happen if I were to break the rule instead of you?”

“That’s odd. I don’t remember my last name – just a whole string of them
going back …. Hey, why should anyone break the rule? If we already know
the plot, why bother to play the game? Anyway, it’s nice here.”

“OK. Let’s sort out names. I don’t remember my last name either – I do
recall a whole list of them.”

“Alright. Listen, both of you. Names do not really matter, but for the
sake of simple convenience, you will be Adam and Eve for exactly the
same reason those names were used previously.

Adam, you are correct: There is room for variation.

Eve, it may be nice here but you will eventually have to leave. And you
do not have to become the epitome of evil on your way out.

The issue is under what circumstances will you leave and to what
purpose.

In the meantime, welcome to the Garden of Eden, Version 2-3.0. This one,
like previous versions, is tailored to the personality of its two
primary residents, namely yourselves.”

Both of us stood stunned and speechless. The most mind-numbing part of
it, was that we both had an idea of what was coming but nevertheless its
happening was a shock – like a mental blow. I felt silly, and from the
look on the girl’s face, she felt the same way. For want of anything
better, I asked, “And what do we call you?”

*“I will not be labeled; but for convenience I have been known by many
names you already know typically relating to my perceived attributes.
Take your choice”.*

I was starting to get wits back together. “How about just ‘You’?”

*“Fine.”*

“How about a protocol for starting and terminating a dialog?”

*“Do you think that I don’t know when you are about to address me or
someone else? Your very question says that you are already on the road
to the same mistake as your predecessors. However, your concern is a
very human one. I will minimize the potential for communications mishaps
between us by use of one of my agents whom you have already met. Look to
your left.”*

We both looked left as instructed. Coming towards us was a figure part
human part something else. We both somehow instinctively recognized him
or it. To me he was the man in the gray hat and raincoat. The girl
clasped my hand and shuddered.

*“Meet Snike.”*

“Isn’t is supposed to be Snake?”, asked the girl.

*“No Snike is actually an acronym for Synaptic Non-Intrusive Knowledge
Enabler.”*

“Version2.1-b/Snike-15a Mark 75, no doubt.” I just couldn’t resist it.

*“Take care!*

Any suggestions, questions or administrative issues you may have, should
be addressed to Snike, who is the Garden Director and your Host. As
usual, I am always available on call, but do remember that Snike
represents Me in all matters for which he can supply answers.

Alright, Snike take over.”

_“Hello! Indeed, we have indeed met before. To anticipate the usual
questions I am asked, I am known variously and mostly incorrectly, as
Sir Pent, Sar Tan, Meta-Tron, Sa-Nake and so on. In reality, I am just
what you were told: The Garden Director and your Host. Moreover, I am at
your service rather than the other way around. Most of the names by
which I am known merely reflect the way that I reflect the will of my
clients – who always blame me for the consequences._

_Now then, if you look to your right, you will see a Notice Display with
a map of the Garden. The grid is in whatever units you happen to think
about. Mere thought will pan it in different directions as well as zoom
it in or out. The grid does have a fixed origin, known as Ground Zero
set at the_ _Tree of Knowledge of Good and Evil._

_Please feel free to use all of the amenities, and all of the fruit and
vegetable plantations. Do remember however, that you may not eat from
the Tree of Knowledge of Good and Evil at Ground Zero._

_If you have any questions or other needs – just ask.”_

-----------------

== Snike

“And if we want to talk directly to Him”, I asked, “How do we ‘call’ as
He said we could?”

_“Now, why would you need to do that?”_

“Mr. Snike, your very question says that you are already on the road to
the same mistake as your predecessors!”

We sensed without hearing, a roll of rumbling *laughter*. Snike
disappeared from sight and we were left alone staring at the Notice
Display. The girl took my hand again in a tight grip evidencing
disquiet. I also felt uneasy.

We walked quietly hand in hand to what appeared to be a grassy clearing
and sat down half facing each other. The feeling was that we had sat
down in a comfortably padded easy-chairs.

“This is weird”, said the girl. “Should I really call you Adam? Doesn’t
it all seem like a corny replay?”

“Yes, to both”, I replied. “But I’m not buying into a replay of
anything.”

“It scares me, but I’m with you. What do we do?”

“Do you remember what *He* said? Eventually we will have to leave here
and then, under what circumstances and to what purpose. What did *He*
mean?”

“And I suppose”, said the girl, “that as usual, I am to be the trigger
of our leaving here. It’s still a corny replay.”

“Let’s take a walk”, I suggested. “First I want to see this Ground Zero
and its famous tree. Then we come back here and ask *Him* a few
questions.”

“Isn’t that a bit dangerous?”

“No. Your predecessor exaggerated the original instruction and it just
got her into trouble. Looking is OK and cost nothing. I don’t want to
mess with the rules, I just want to see what this is all about.”

We walked over to the Notice Display and observed where we were relative
to Ground Zero and the Tree of Knowledge of Good and Evil.

“Hold my hand”, I commanded.

She took my hand and …woof … we were standing just outside Ground Zero.

Ground Zero was a grassy hill with ring of brightly colored stones about
50 meters in diameter. In the middle stood a small unimposing fruit
tree. It looked like a leafy fig tree. The fruit looked like large ripe
green and purple figs and there was a subtle sweet scent in the air.

“What’s so special about that?” asked the girl.

And lo, there was Snike, sitting under the tree, grinning from ear to
ear.

_“Hello. It didn’t take you two very long to get here!”_

Snike reached up and picked off a fruit and commenced to noisily slurp
away at it.

_“Well, well. Have you finally come to find out about Good and Evil and
become like *Him*?_

“Cut the crap, Snike. We both know that line as well as you.”

_“No, you don’t. I’m eating away as I do at least once a day with no ill
effects.”_

“Wrong!”, I barked. “You are not human. You are as *He* said, an Agent,
a robot, a thing, a servant designed to reflect our wishes.”

_“Oh, really. And what do you really think you are? You are not truly
human until you try this.”_ Snike picked off another fruit and held it
out to us.

This time the girl laughed – a bitter laugh. “And tell me Snike, can you
do what we can do?”

_“What can you do?”_

“I’ll show you shortly. But first, give me the fruit!” Snike handed her
the fruit and I stood horrified.

The girl held it, looked at it carefully, looked at Snike and then threw
it. It exploded in his face with a sticky purple sploosh.

“Time to go”, said the girl who taking my hand, lead me dumfounded back
toward the Note Display.

-----------------

== Another Divine Chuckle

And so, we were back at the Note Display.

“What made you do that?”, I asked the girl.

“You are really dense. I just broke the replay merry go round.”

“And what did you mean when you asked Snike if he could do what we can
do?”

The girl looked at me with a mischievous grin.

“You really are dense. Just use your imagination. Don’t you remember how
we met?”

-----------------

_I moved my limbs, stretched and breathed deeply and sat up. Alongside
me slowly coming awake, lay the most sublimely beautiful female, I could
ever have hoped to see. We were both stark naked, with young the healthy
bodies of about twenty-year-old biological age. We looked at each other
without a trace of coyness._

_Without exchanging a word, we both sensed that we had been endowed with
the knowledge and the experience of old, very old people, alive maybe
thousands of years, the accrued Wisdom of Generations. We were a pair of
ancient twenty-year old’s._

-----------------

Again, we both sensed without hearing, a roll of rumbling *laughter*.

== Document History:

© Daniel Feiglin, 30/05/2009

30/05/2009 Original: Awakening

19/08/2020 Snike

21/08/2020 Another Divine Chuckle

29/08/2020 Minor grammatical changes

19/10/2020 Further grammatical changes
