10/08/03, Sunday י"ב אב, תשס"ג

== Billy and Hubris Express

By Daniel Feiglin

A railway yard is a very interesting place. When Billy was a little
fellow his mummy would walk with him along the wall where, through a
crack, he could see the trains whizzing by.

Billy grew older, and he would visit the crack by himself. Now he could
see through clearly and was able to distinguish between different kinds
of trains – freight trains, passenger trains and maintenance trains with
interesting special equipment. He could also watch a little of what was
going on inside the yard. Inside the yard there were crews who cleared
the weeds from between the tracks and replaced gravel to the beds. There
were crews who maintained the tracks themselves. Billy thought that they
were very lucky. They could look up and down the lines and see trains
coming in and leaving. A really skilled railway maintenance man could
follow the tracks by eye, and to about a hundred meters he could see to
which line a passing train would be switched.

On the far side of the railway yard there was a long building about as
high as a two storey house with barred windows along its length. If
Billy could have seen the entrance door, he would have observed a sign
saying, “Entry only to authorized personnel”. The building housed the
control room, full of wheels and levers connected to the switches, to
enable trains to be routed in and out of the yard. Billy would have
loved to be in the control room. The people there saw everything in the
yard and on the new electric display board. They could see all the
incoming trains, and they controlled exactly where they had to go.

Billy didn’t know much about what went on in the luxurious office block
behind the yard housing management. But somewhere, in one of the top
floors sat the General Manager who also had the power to build new lines
and remove unnecessary ones.

One day, Billy noticed a new crack in the wall. With a bit of pushing
and squeezing, he was able to slip through into the railway yard. What a
wonderful feeling! Now he could see all the trains entering and leaving.
Enraptured, he started walking across the yard, crossing track after
track. The sound of an incoming passenger train caught his attention.
Just at that moment, the railway crew foreman, also momentarily
distracted by the sound glanced around, and saw Billy, standing in the
middle of a track mesmerized by the view of the oncoming passenger
train.

“Hey kid!” he yelled, “Get off the track!” But Billy didn’t hear a
thing. The foreman, too far away to grab Billy, made a dash for the
control room bounded inside, and after a quick glance at the board
pulled a lever. The incoming passenger train switched to a parallel
track missing Billy, who was immobile with fascination. The foreman
raced out of the control room, towards Billy who now realized that
something was afoot. He scooped up Billy in his arms, took him to the
nearest exit and sent him off home with a stern warning as what would
happen if he ever again found him inside the railway yard. Everyone
congratulated the foreman on his initiative and quick reaction.

[.underline]#Hopeful story ending:#

Half an hour later the train switched back to its normal track and
arrived safely at its destination.

The foreman got a commendation and a pay rise.

[.underline]#Normal story ending:#

Half an hour later the passenger train smashed head-on into an
approaching freight train instantly killing the driver, 300 passengers
and injuring many more.

The foreman was fired.

[.underline]#Non-normal (Happy) story ending:#

Half an hour later the passenger train was signaled to an emergency stop
by a policeman. On the track were police vans, fire trucks and military
vehicles. They were removing a suspicious object, maybe a bomb, left
under the track. The passenger train driver stepped out onto the track
and walked towards the police cordon to watch. To his surprise he found
himself face to face with the driver of a freight train parked a
kilometer on the other side of the cordon.

Nobody remembered the foreman.
