Document History

20/10/2023 Commenced

©Daniel Feiglin, 2023

dilogsys@inter.net.il

{empty}(052) 386 9986

== The Simchat Torah War – 5784/2023

At the time of writing this, the Simchat Torah War is in full swing. Now
it mainly directed at wiping out Hamas in Gazza with occasional
skirmishes with Hezbollah in the north. But anyone with eyes can see
that what is going on is just a tiny peep in the cauldron of a major
clash of civilizations. The lineup appears to be Russia, China, North
Korea, Iran and proxies versus Israel. Of course, the Western world will
line up with Israel with sympathy and bad advice. The USA has and will
send ammunition resupply and other items of ordnance principally because
her own neck is on the block should Israel be defeated. But the world
(including Israel) has no idea of what is really coming.

== Miracles – Overt and Hidden

I want to make a short digression: a Histriosophic discussion based on
several Kabbalistic ideas.

The Creation story that commences the Torah defines seven periods of
which the seventh period concerns us. It is the period of our universe.
It is the period during which the Creator “rests” (Shabbat), for most
part allowing things to run. However, the Creator constantly monitors
what is happening, particularly in the human world.

From this point, I take the position of Israel alone.

Under what conditions does the Creator “break” his Shabbat and actively
interfere? The answer is פיקוח נפש. If Israel is in mortal danger, the
Creator may implicitly interfere using what we call a נס נסתר. A famous
example of that is of course, the Purim story. A famous counter-example
of that is apparent non-interference during the Shoa. Or was it?

There is further condition required for such interference but as a נס
גלוי: That is, if הירושה בסכנה. The ירושה in question is that endowed to
Abraham in the ברית בין הבתרים. We began to see that in action during WW
II at the second battle of El-Alemein late in 1942, when Montgomery
turned back Rommel’s army. Montgomery was outgunned and outnumbered and
had serious trouble getting supplies.

The fledgling Yishuv in (then) Palestine was in danger of being overrun
by Rommel’s forces. Hajj Amin al-Husayni, the Mufti of Jerusalem had
already arranged with Eichmann to set up a concentration camp to murder
the Jewish population, in Emek Dotan.

But unexpectedly, Rommel was defeated. The ירושה was saved.

The same can be said of Israel’s 1948 War of Independence, the 1967 Six
Day War and the 1973 Yom Kippur War.

== Where are We Now?

Once again, we have a world lineup against us. Whereas most of the
Western World recoiled with disgust from the Hamas atrocities, no one
except the USA has done anything constructive to help. But even here we
must be careful: Bidens’s presidency is at best fickle. Considering the
disastrous Afghanistan pullout, the disastrous situation on the US’s
southern border, their idiotic energy policy, and their inept handling
of the US economy – we cannot expect much from Biden et al.

Once again, the ירושה is in danger.
