Contents

Document History link:#_Toc124258190[2]

{empty}1. Preface link:#preface[3]

{empty}2. Introduction link:#introduction[3]

{empty}3. Life Matrices link:#life-matrices[3]

{empty}4. The “Tentacles of Providence”
link:#the-tentacles-of-providence[5]

{empty}5. Communications link:#communications[5]

{empty}6. Consequences link:#consequences[5]

{empty}7. Next Steps link:#next-steps[6]

== Document History

‏‏25/02/2021 Original

21/04/2021 First draft

24/04/2021 Editorial review & corrections

26/12/2022 Editorial review, change to General_Use.dotx template

11/12/2024 Minor edits

©Daniel Feiglin, 2021-2024

dilogsys@inter.net.il

{empty}(052) 386 9986

== Preface

This Note is a further development of Note 03-02. It does not however,
refer to this or other Notes in this series. It is completely
self-contained.

== Introduction

In what follows, we describe a “soul” model of sorts that provides a
rational framework (also of sorts) in which some elements of the worlds
of reality and ideals are reproduced, and against which, prophecy has a
minimally intelligible meaning.

All that notwithstanding, woe betide anyone stupid enough to equate the
model to reality. It is only of interest if it reflects something of our
world of thought, and points to further insights, which may of
themselves obsolete the model.

I am going to propose that a living organism might be seen as having a
"life proximity" field around it, without attempting to say just what
the field is. I based the idea on very simple empirical considerations.
For short I call it the *life matrix*.

Further, I suggest that the field attenuates further out from the
organism; in its immediate vicinity it is very strong and the space time
region in or around the physical body could be viewed as the interface
between the familiar physical world and the "whatever lies beyond".
"Whatever lies beyond" is perceived by us through the filter of our
religious predilections (or perhaps lack of them). In any event, it was
the various conceptions of the "whatever lies beyond", which gave rise
to most religions as we know them.

Common to most such beliefs is the view that death is the severing of
the physical organism from the life matrix, and so we pass to the almost
universal religious preoccupation with death and what might lie beyond
it. In this respect Judaism follows the pattern, although unlike other
religions, it has no really "official" view on the subject, despite the
wealth and variety of death-related customs.

Jewish tradition refers to five levels of "spirit”: נפש, רוח, נשמה, חיה
יחידה. The first נפש, is considered to be the closest element of the
"spirit" to the physical organism, and יחידה the farthest. (The earliest
source of this idea is found in the Midrash Rabba.footnote:[מדרש-רבה
(יד,יא): "חמישה שמות נקראו לה, נפש רוח נשמה יחידה חיה" (בחסידות הסדר הוא
"חיה יחידה"). אלה לא רק שמות ומלים נרדפות, אלא חמישה רבדים שקיימים
בנשמה; חמש דרגות, זו למעלה מזו.])

For my purposes this is grossly over simple. The life matrix is like an
onion with many layers, starting with those closest to the center being
biologically biased compared to those further out, being "other"
biasedfootnote:[I develop these ideas more fully in my Prophecy Notes,
series 1-1 to 1-8. What I have above is sufficient for this Note.].

I will call a *life form*, any physical entity capable of hosting a life
matrix.

== Life Matrices

I make the following postulates about life matrices:

[arabic]
. Every life matrix will attempt to occupy the first available life form
capable of holding it
. A life form may have sufficient capacity for more than one life matrix
. Several life matrices occupying one life form will for most part blend
into a single entity. Life matrices are only discrete insofar as they
are associated with a specific life form.
. In the case of sentient beings, each personalityfootnote:[We all have
“multiple personalities” that we use for different purposes. A healthy
person will have one dominant personality. A schizophrenic will have two
or more dominant personalities.] may, but not necessarily be treated as
separate life forms
. Personality boundaries in a sentient being are dynamic, particularly
at early ages, and only reach noticeable stability with maturity and
increasing age. Thus, the correspondence between the components of an
individual’s life matrix and its personality structure is somewhat
variable.
. Life follows a conservation law: The totality of life as expressed by
life matrices is constant. Life itself cannot be created or destroyed.
It may only be transferred. (By way of contrast, a life form may be
destroyed.)
. The life matrix of a sentient being may be eroded. Typically, this
occurs when one sentient being steals the energy of a second sentient
being. (Competition)
. The life matrix of a sentient being may be expanded. Typically, this
occurs when one sentient being acts for the general welfare of those
about it. (Cooperation)
. Elements of an eroding the life force matrix can be relocated subject
to ‎1 above. Some of them may find their way to an expanding life matrix
. A life matrix in a sentient being, which does not erode or expands,
maintains identity. It will always find an equal or better sentient
being to hold it (“Reward”)
. A life matrix in a sentient being, which erodes, may not necessarily
find its next abode in a sentient being. All depends on the extent of
erosion (“Punishment”)
. There are no external restrictions on a sentient being (apart from the
physical laws governing the fabric of the universe), as to whether it
expands or erodes its life matrix.
. None of the processes surrounding the allocation of life matrices to
life forms, sentient or otherwise, are subject to perceived time and
space. (Paradoxes are impossible.)
. Life matrices have a form of identity. A sentient life form is rarely
if ever “conscious” of such identity, which is outside time and space.
Such an identity may include elements of other constituent identities.
The identity is only pertinent to communication between the host life
form and the Creatorfootnote:[In Kabbalistic jargon, identities are
maintained at the level of Olam HaYetzira but usually no higher.].
. Life matrices have no form of continuity. Life matrices of themselves
do not have any physical characteristics. In particular, they carry no
humanly perceptible information when re-appearing in successive life
forms.

In formulating points 1-15 I have not attempted to make them either
mutually exclusive (i.e., there is overlap between them) or mutually
exhaustive (i.e., not all contingencies are covered). To do otherwise
would be very hard if not impossible. What is obvious is that they
contain elements of the common הישארות הנפש hypotheses.

Item ‎6 effectively says that man will never be able to create life i.e.,
there is no way man will be able to take some carbon, hydrogen and
oxygen atoms, push them into one side of a black box, and have a little
"creepy" crawl out of the other side. What we may be able to do, is take
those same atoms, and transfer life from something already living, much
as you light one candle from another - but no more. Item ‎6 says that
life is an elementary irreducible building block of the universe, which
cannot be "created" any more than you can create space-time. The sooner
we learn how to build it into our field equations, the sooner we might
see some real scientific progress. (We might even see some moral/ethical
progress, but that would be asking too much ...)

It also says that killing a life form terminates its existence as a live
physical entity, but not its life matrix, which is transferred elsewhere
(and “elsewhen”!).

== The “Tentacles of Providence”

So far, we have taken a human-centric approach to the Man-Creator
relationship. It is impossible to accurately map the reverse
relationship. What we offer then, though far from accurate, is not
completely wrong and maybe adequate to formulate some basic ideas.

Each life matrix may be thought of a projection of the Creator into the
material universe. The interface between the Creator and creation is
precisely the collection of life forms. It is no surprise therefore,
that we have found it difficult to incorporate life forms into our
science since they are quite observable but not measurable.
Measurability is blocked by the life matrix not being of the physical
universe. (Put in Kabbalistic terms, scientists can only bump their
heads on the ceiling of מלכות דעשיה but can never get beyond
it.)footnote:[These “tentacles of providence” into the real world go
much further that the “hairs on the beard” of the Idra Rabba, which are
“pipes” – communication channels and little more.]

== Communications

The concepts of sections ‎2 and ‎3 provide the minimum infrastructure
needed to “sensibly” discuss communications between the Creator and life
forms. The most elementary communication is the very act of creation and
sustenance. For a sentient life form – man, it goes further:

* For man, communication with the Creator is not an “option”; it is
essential. His life matrix, or soul for short, is “a little piece of the
Creator from above”.footnote:[חלק אלו-ה ממעל]
* Man relating to himself, is also in a very small way, the Creator
“talking to himself”.

There is also “inanimate” communication between the Creator and the
physical universe. Suppose that it started in “big bang” from an
infinitesimal point, expanding into what we see around us (and maybe
still expanding). What stops it from collapsing back into an
infinitesimal point? The material universe has ongoing *extent* as
allowed by the Creatorfootnote:["המחדש בטובו כל מעשה ברשית"]. To claim
that the universe maintains its structure due to “physical laws” merely
begs the question.

There are therefore, two levels of communication between the Creator and
creation: animate and inanimate. Animate communication is very
subjective can cannot be encapsulated in mathematical formulations.
Inanimate communication can be described using the language of
mathematics.

== Consequences

Conscious communication between man and the Creator is נבואה/תפילה. Man,
speaking is called תפילה. The Creator speaking is called נבואה. There no
problem with such communication; it goes on all the time. It takes
conscious organized effort to “switch it off”.

Most of us don’t want it since it implies responsibility. We use all
kinds of devices to suppress it, to silence it because it leads to a
level of personal discomfort. It is much easier to isolate (educate?)
ourselves in layers of righteous ritual to replace it and then pay
lip-service to its restoration. You do that three times, five times a
day or just once a week (or less). But one thing is certain: The
נבואה/תפילה “line” is silenced.

Of course, after a lifetime of avoidance (starting from childhood) it
not surprising that most of us who become aware and interested, find it
hard if not impossible to “get back into it”.

All that said, נבואה is not some kind of fortune-telling. It offers a
precise and deep view of the here-and-now. Unsurprisingly, it can lead
to a very accurate assessment of “where things are going”.

But there is a caveat: נבואה when it does get through, can be heavily
biased, filtered and amplified by irrelevant superstitions and religious
preconceptions leading to nonsensical conclusions. According to Jewish
tradition, the first person to understand all this was Abraham.

== Next Steps

My Life Matrix concept is a super-set of what traditional religious
belief calls the “soul”. In my next Note, I will narrow down the
discussion to human Life Matrixes – very close to the “souls” idea and
ask an almost intractable question about them.

See also, my short story,footnote:[Added below for convenience.] _The
Great Conversation._

It starts immediately after. There is no time delay. There is simply, no
time. It is not conducted in any language. There is no language. It is
something like a dream, but absolutely coherent and consistent.

If I am prepared and fast enough to ask the first question, then I will
progress and grow. I am (as this document attests) prepared. Were I not
prepared, I would be asked the first question. I would then be on the
defensive and slowly get whittled down by a barrage of follow-up
questions.

There seems here to be identity (or I would not be writing this) and
discernable continuity even if it cannot be expressed in language.

So, for my first question: The material universe seems to be in a very
general sense, deterministic. Sentient life (man) was injected into it
in a way that gave it a consistent environment for decision making. Is
that view correct? If not, what is the situation?footnote:[Motivation:
Were that not true, man could not be held responsible for his actions.]

I get an answer: “*That is the right direction.*”footnote:[Manitou]

And then I follow-up: Then all evilfootnote:[רשע as distinct from רע.]
in the universe is generated by man?footnote:[Motivation: If the wind
blows over a tree that falls on someone and kills him, that is just
[possibly avoidable] bad luck. If a stadium or building collapses
killing and injuring many people, that is bad luck tainted with evil.
The stadium or building owners were negligent. If armed robbers kill
people during their attempt to rob a bank, that is pure evil. As in
footnote 3.]

“*Yes!*”

“*Now I will ask a question: Did you leave the world a better place for
your having been there?*”footnote:[Compare with, שבת דף ל"א עמוד א:אמר
רבא: בשעה שמכניסין אדם לדין, אומרים לו.... My one question applies to
any human being. Obviously, I expect that *He* takes into account age,
level of responsibility etc.]

“How should I know? Can I judge myself?”

“*Alright. Let’s see. On April 28, 1958 you did this ...*”

And so, continued a dreary list of my foibles and follies over the
years. It even included one or two good things I seem to have done.

“*What do you have to say?*”

“I must have been quite an evil little fellow. But at least I didn’t sit
back and do nothing during the murder of one and a half million children
between 1940 and 1945.”

“*WHAT! DO YOU PRESUME TO JUDGE ME?*"

____
א**ֵיפֹה הָיִיתָ בְּיָסְדִי אָרֶץ הַגֵּד אִם יָדַעְתָּ בִינָה?**

*מִי שָׂם מְמַדֶּיהָ כִּי תֵדָע אוֹ מִי נָטָה עָלֶיהָ קָּו?*

*עַל מָה אֲדָנֶיהָ הָטְבָּעוּ אוֹ מִי יָרָה אֶבֶן פִּנָּתָהּ*footnote:[Job, 38:4-6]*?*
____

“I have heard that answer before. And I claim that it is not an answer,
but an evasion. I might be but of small accountfootnote:[Job, 40:4], but
this time I will answer:

Five thousand years ago because of rampant evil, you destroyed humanity
in a flood. The only remembrance of it is from Noah and his descendants.

About 3,800 years ago because of rampant evil, you destroyed Sodom and
Amora in a hail of fire and brimstone. The only remembrance of it is
from Abraham and his descendants.

If you do not like my answer, wind back time so that I never existed.
That way my rampant evil will be removed without any remembrance and
this conversation will never have taken place. If however, you do this
thing, then my last thought is, I am sorry for you.”

“*You are sorry for me?*”

“Yes. At long last you will have created something – me, that was a
total failure and that had to be rolled back out of existence. Worse
than the generation of the flood, and the people of Sodom.”

“*You are impertinent and stubborn but you have striven with God and man
and prevailed.*footnote:[Bereshit 32:29 and Baba Metzia 59/2 (התנור של
עכנאי)] *So here is my judgement: You will go back to the world of the
living and your assigned task will be much harder. But you will take
with you a gift that will enable you to succeed. You mentioned the
children murdered between 1940 and 1945: You will take with you a
soul-fragment of each one of them*.”
