Contents

Document History link:#_Toc124258229[2]

{empty}1. Introduction link:#introduction[3]

{empty}2. The Life Matrix Interface link:#the-life-matrix-interface[4]

{empty}3. Back to the Leshem link:#back-to-the-leshem[5]

{empty}4. What is the Mechanism? link:#what-is-the-mechanism[5]

{empty}5. Postscript to Abraham’s Tripod
link:#postscript-to-abrahams-tripod[5]

== Document History

‏09/08/2021 Original

17/08/2021 First draft additions

26/12/2022 Editorial review, change to General_Use.dotx template

11/12/2024 Minor edits

©Daniel Feiglin, 2021-2024

dilogsys@inter.net.il

{empty}(052) 386 9986

== Introduction

This Note continues the theme of Note 04-07 against the backdrop of
remarks by the Leshemfootnote:[לשם שבו ואחלמה, הקדמות ושערים: Barzani
edition, 2006], Sha’ar 6, Chapter 5, page 49 commencing, אמנם דע.

Before commencing, I need to take a stand on the Leshem’s apparent naive
recounting of Medieval and Renaissance concepts from the Zohar, the Ari
and others. Mentioned also, are other notations that sit better in
Christian thinking rather than in Hebrew thinking. The best example is
the frequent mention of the Seven Portals of Hell.footnote:[שבע מדורי
גיהינום]

Anyone with even a passing exposure to the Leshem’s other works knows
him to be an organized and thorough writer who uses a “spiral” method of
teaching. The Leshem makes use of Kabbalistic terminology in his own
way, demanding that his readers take care not to superimpose concepts
learned from other Kabbalistic sources – not the least being the Ari.
The Leshem also departs from the Lurianic teaching in serious ways two
of the most noticeable being:

* A histriosophic interpretation of Kabbalistic “processes”
* A rework of these very processes that has little room for the Breaking
of the Vesselsfootnote:[שבירת הכלים]

It is my feeling that the Leshem uses the הקדמות ושערים just to get the
reader accustomed to the traditional jargon – and then be prepared to
question it just as I will do here. My remark is based on the Leshem’s
frequent forward references to his other works some of which take a
completely different line of thought.

The section in the Leshem that I referred to in my opening paragraph
discusses the difference between Israel and the Nations. On the surface,
it follows an old traditional line of thought and finishes rather
abruptly.

The Leshem passed away in 1926 at the age of 85. His lifetime spanned
the beginning of modern era. He is believed to have been well versed in
both the science and philosophy of the late 19^th^ and early 20^th^
centuries. He could not but have been aware of early Genetics. So, his
claim that all Jews alive are descended from the three forefathers is
palpable nonsense – unless you take his words as an invitation to read
between the lines and ask, under what circumstances might his remarks
make sense. Coming from the Lithuanian Ultra-Orthodox school, the Leshem
had to be somewhat circumspect, so he abruptly halted his discussion of
the subject in a way that would ruffle no feathers but still be a
“flashing red light” to someone from a later age and a different
background.

I sometimes suspect that the Leshem wrote for a future audience that
would not hesitate to strip off layers of “old peel” for what was
underneath. He was perfectly aware of the risk that the future reader
would not be “savvy” enough to get to the core of things and just give
up. That was the risk he took as expressed by his occasional injections
of the words,

*“" והוא רחום יכפר עון....*

With the Leshem in the background, I continue from Note 04-07.

== The Life Matrix Interface

Any discussion about “souls” invites the reader to overlay it with a
cloak of his preconceptions and religious dogmas. I will therefore
continue with the Life Matrix terminology and introduce two further
terms: A Human Life Matrix, which is just what it says. A Human Life
Matrix is associated with a Human Life Form or just a human being.

(How well a Human Life Matrix confirms to the human soul idea, does not
interest me.)

In Note 04-07, I treated the Life Matrix at least insofar that it
relates to humans, as a completely homogeneous entity. Such a
comfortable framework is not on the face of it, supported by history. We
are confronted by over 5000 years of history that says that the
descendants of a “primordial man” traditionally called Adam, through the
generation of Noachides down to the emergence of Abraham and his
descendants, produced a human group that was somehow different from the
rest of mankind into which it substantially assimilated. It left a tiny
but hard-core group of people who claimed direct descent from Abraham.

The common thread of this group, down do our time is the acceptance of
“Abraham’s Tripod”, three elementary but fat reaching ideas: (1)
Prophetic (2) Moral (3) Monotheism.

This group styles itself variously as Israel, Hebrews, Jews depending
more on political proclivities than any serious differences relating to
Abraham’s Tripod itself. I will refer to the group collectively, as
“Israel” or the “Jews”.

And so, what makes Israel “different” from the rest of humanity? How did
Israel survive, particularly, the last 2000 years?

If we are to understand the “flashing light” left to us by the Leshem,
we need to look for something genetic. The Leshem looks to the Human
Life Form as supported by the Torah narrative.

If we are to believe traditional sources going back 2000 years, then we
need to look for some kind of “Jewish soul”, a Human Life Matrix. The
Human Life Matrix approach came through the Kabbala in the face of
ongoing oppression – including widespread abuse of Jewish women.

But we will be looking in vain.

My claims about the Life Matrix in Note 04-07 stand. The Life Matrix of
a human being is not dependent on race, creed or any other human
characteristics. However, the way in which a Life Matrix interacts with
its host Life Form is far from uniform.footnote:[There are shades of the
אור וכלי concept in this.]

There are plenty of indications (but no conclusive proof) that Jews have
certain genetic characteristics (if only of “Jewish” diseases like
Tay-Sachsfootnote:[See for example,
https://medlineplus.gov/ency/article/001417.htm. “Anyone can be a
carrier of Tay-Sachs. But the disease is most common among people with
Ashkenazi Jewish ancestry. One in every 27 members of the population
carries the Tay-Sachs gene.”]). The sub-group of Cohanim appear to have
a well-known genetic marker of their own. In recent years, the Israeli
Rabbinate has been using genetic data to assist determining Jewish
antecedents in the absence of any documentation or other evidence.

I propose that something in the human genetic structure provides the
“human” side of the interface with the Life Matrix. What it is, I have
no idea and I doubt whether we will ever find it beyond knowing that
it’s there. Remember that a great deal of Kabbala deals with the
interface between man and his Creator and between the universe and its
Creator – without much success. (The Leshem had a good try in his other
works.)

The reason that I mention it at all, is that there is an impact of the
Life Matrix on the genetic structure. It does not change human behavior
but for anyone with the Jewish genetic structure, it opens up a type of
responsibility. The internal form of that responsibility is expressed by
Abraham’s Tripod.

The external form of that responsibility is the set of consequences
arising from the Tripod becoming the beacon to what emerged as Israel.

That does not mean a non-Jew cannot internalize and function based on
Abraham’s Tripod. A non-Jew simply does not have an a-priori
responsibility to do so.footnote:[See Wikipedia:
https://he.wikipedia.org/wiki/%D7%92%D7%93%D7%95%D7%9C_%D7%94%D7%9E%D7%A6%D7%95%D7%95%D7%94_%D7%95%D7%A2%D7%95%D7%A9%D7%94_%D7%9E%D7%9E%D7%99_%D7%A9%D7%90%D7%99%D7%A0%D7%95_%D7%9E%D7%A6%D7%95%D7%95%D7%94_%D7%95%D7%A2%D7%95%D7%A9%D7%94]

A גר-צרק is no different than any other non-Jew. The process of
conversion only affects family and communal relationships. The kind of
a-priori responsibility described above cannot be acquired; it will
however “kick in” if the descendants of גר-צדק marry into genetically
Jewish families.

Conversely, Jews who marry out (male or female) will endow their
descendants (halachically Jewish or not) with the Jewish genetic
structure carrying the “responsibility” element.

== Back to the Leshem

In a way then, the Leshem was right. But only in a way. Based on the
foregoing, all the descendants of the Twelve Tribes are Jews – not just
the male line as claimed by the Leshem. The twelve sons of Jacob married
Canaanites (Judah), Egyptians (Joseph) and others married Midianites
(Moshe, Pinchas). Of course, what has happened since then, is well known
history. We must recognize that the occurrence of the Jewish genetic
structure is far more widespread that the 18 million or so Jews in the
world today. What Halacha will do with that over the next 50-100 years
is another matter.

== What is the Mechanism?

The Jewish genetic structure is the “trigger” that makes a certain
“mind-set” based on Abraham’s Tripod “potentially” available from the
Life Matrix. The “potentiality” is activated by a straight forward
educational process, preferably from childhood. To some extent it has
been eroded and distorted over the last 2000 years but somewhere, it is
still there.

== Postscript to Abraham’s Tripod

Recall that Abraham’s Tripod is: (1) Prophetic (2) Moral (3) Monotheism.

A tripod is the simplest free-standing structure. Remove one leg and it
topples over.

[arabic]
. The Christians “toppled it” by dropping the Monotheism leg with their
“three is one” and “one is three”.
. The Muslims “toppled it” by dropping the Moral leg. Nowhere in the
Quran will you find the two magic words, “לא תרצך”.
. The Philosophers “toppled it” by denying the Prophetic leg. To them,
there is no such thing as valid information beyond our senses.
